### ISSUE TITLE
Block confirmation for every coin

### ISSUE THREAD

**Issue by metal32** [WazirX/wazirx-api#1]
Guys thanks a lot for providing the endpoint for market status API, Is it possible that you guys can also provide the number of block confirmation required while depositing any coin inside that API only?
Would be a great help! Thanks in advance

**Comment by BuddhaSource** [comment]
Oh yes, what a coincidence. We are just testing this as we speak. Should be live today.

**Comment by BuddhaSource** [comment]
This is done and live.

**Comment by metal32** [comment]
Thanks again @BuddhaSource

**Comment by BSGILL012** [comment]
Thanks again

**Comment by BSGILL012** [comment]
Oh yes, what a coincidence. We are just testing this as we speak. Should be live today.
👍 1
